spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase-changeLog.xml